// Downloads each team's flag once and bakes them into lib/flags-data.ts as
// base64 data URIs.
//
// Why baked-in: an SVG loaded as a README <img> cannot fetch external resources
// (browser security), so flags must be embedded inline. Re-run after editing
// the team table: `npm run build:flags`.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { FLAG_CODES } from "../lib/teams.js";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "..", "lib", "flags-data.ts");

// flagcdn 80px-wide PNGs: crisp at the ~26–46px sizes we render, ~1–3 KB each.
const flagUrl = (code: string) => `https://flagcdn.com/w80/${code}.png`;

async function fetchFlag(code: string): Promise<string | null> {
  try {
    const res = await fetch(flagUrl(code), {
      headers: { "User-Agent": "wc26-widget" },
    });
    if (!res.ok) return null;
    const buf = Buffer.from(await res.arrayBuffer());
    return `data:image/png;base64,${buf.toString("base64")}`;
  } catch {
    return null;
  }
}

async function main(): Promise<void> {
  const entries: Array<[string, string]> = [];
  let missing = 0;
  for (const code of FLAG_CODES) {
    const data = await fetchFlag(code);
    if (data) {
      entries.push([code, data]);
      console.log(`✓ ${code} (${(data.length / 1024).toFixed(1)} KB)`);
    } else {
      missing++;
      console.error(`✗ ${code} — no flag found`);
    }
  }

  const body = entries.map(([k, v]) => `  "${k}": "${v}",`).join("\n");
  const file =
    `// AUTO-GENERATED by scripts/build-flags.ts — do not edit by hand.\n` +
    `// Base64 PNG flags (flagcdn w80) inlined so README <img> SVGs need no network.\n` +
    `export const FLAGS: Record<string, string> = {\n${body}\n};\n`;
  writeFileSync(outFile, file, "utf8");

  console.log(
    `\nWrote ${entries.length} flags to lib/flags-data.ts` +
      (missing ? ` (${missing} missing — those teams fall back to code chips)` : "")
  );
  if (entries.length === 0) process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
